// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: 'AIzaSyCWTIbQHzIh4TlYO4X_teQ_k7W6JLNs7cU',
        appId: '1:124242284599:android:c795020e6a1a8dc97f2fb2',
        messagingSenderId: '124242284599',
        projectId: 'ageraliment-af637',
        storageBucket: 'ageraliment-af637.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: 'AIzaSyDfeph76kZ56z3Ni_Png-BU-xcY2SQqAtw',
        appId: '1:124242284599:ios:1120390651b26b3c7f2fb2',
        messagingSenderId: '124242284599',
        projectId: 'ageraliment-af637',
        storageBucket: 'ageraliment-af637.firebasestorage.app',
        iosBundleId: 'com.drive.trust.driveTrust',
      );
}
